# Copyright © 2018-2025 Johan Cockx, Matic Kukovec & Kristof Mulier
# SPDX-License-Identifier: LicenseRef-Proprietary
#
# All rights reserved.
"""
Auto‑generated stub for the external module  *source_analyzer*.
Placed next to sourceanalyzerinterface.py so that PyCharm can
find the symbols and offer code‑completion.

Also placed in:
- components/
- gui/forms/
- gui/helpers/
"""

from __future__ import annotations

import enum
from typing import Any, Callable, Dict, List, Optional, Sequence, Set, Tuple

# ────────────────────────────────
# Exceptions
# ────────────────────────────────
class ClangRestrictedCallbackError(Exception): ...

# (any other custom exceptions can be added here)

# ────────────────────────────────
# Enumerations
# ────────────────────────────────
class ProjectStatus(enum.Enum): ...  # READY | BUSY | ERROR
class LinkerStatus(enum.Enum): ...  # WAITING | BUSY | DONE | ERROR
class FileMode(enum.Enum): ...  # EXCLUDE | INCLUDE | AUTOMATIC
class FileKind(enum.Enum): ...  # OTHER | EXECUTABLE | … CPLUSPLUS
class HdirMode(enum.Enum): ...  # EXCLUDE | INCLUDE | AUTOMATIC
class InclusionStatus(enum.Enum): ...  # EXCLUDED | INCLUDED
class AnalysisStatus(enum.Enum): ...  # NONE | WAITING | BUSY | DONE | FAILED
class OccurrenceKind(enum.Enum): ...  # DEFINITION | DECLARATION | …
class LinkStatus(enum.Enum): ...  # NONE | UNDEFINED | DEFINED | …
class Severity(enum.Enum): ...  # WARNING | ERROR | FATAL
class Category(enum.Enum): ...  # NONE | TOOLCHAIN | MAKEFILE

# ────────────────────────────────
# Core classes
# ────────────────────────────────
class Project: ...
class Hdir: ...
class Symbol: ...
class Location: ...
class Occurrence(Location): ...
class FileOccurrence(Occurrence): ...
class SymbolOccurrence(Occurrence): ...

# ────────────────────────────────
# Public helper functions
# (signatures are relaxed with Any for brevity)
# ────────────────────────────────
def command_list2string(cmd: Sequence[str]) -> str: ...
def export(
    function: Callable[..., Any] | None = ..., *, fallback: Any | None = ...
) -> Any: ...
def project_status_name(status: ProjectStatus | int) -> str: ...
def linker_status_name(status: LinkerStatus | int) -> str: ...
def file_mode_name(mode: FileMode | int) -> str: ...
def file_kind_name(kind: FileKind | int) -> str: ...
def hdir_mode_name(mode: HdirMode | int) -> str: ...
def inclusion_status_name(status: InclusionStatus | int) -> str: ...
def analysis_status_name(status: AnalysisStatus | int) -> str: ...
def entity_kind_name(kind: int) -> str: ...
def symbol_kind_name(kind: int) -> str: ...
def entity_kind(name: str) -> int: ...
def print_all_entity_kinds() -> None: ...
def occurrence_kind_name(kind: OccurrenceKind | int) -> str: ...
def link_status_name(value: LinkStatus | int) -> str: ...
def severity_name(value: Severity | int) -> str: ...
def category_name(value: Category | int) -> str: ...
def user_occurrence(*args: Any, **kwargs: Any) -> Occurrence: ...
def set_number_of_workers(n: int) -> None: ...
def get_number_of_workers() -> int: ...
def start() -> None: ...
def stop() -> None: ...
def abort() -> None: ...
def init(
    so_path: str,
    debug_print: Callable[..., Any] | None = ...,
    debug: bool = ...,
) -> None: ...

# ────────────────────────────────
# Exported constants (typed as Any to avoid maintenance overhead)
# ────────────────────────────────
occurrence_kind_definition: Any
occurrence_kind_tentative_definition: Any
occurrence_kind_weak_definition: Any
occurrence_kind_declaration: Any
occurrence_kind_weak_declaration: Any
occurrence_kind_use: Any
occurrence_kind_weak_use: Any
occurrence_kind_include: Any
occurrence_kind_none: Any
file_mode_exclude: Any
file_mode_include: Any
file_mode_automatic: Any
hdir_mode_exclude: Any
hdir_mode_include: Any
hdir_mode_automatic: Any
severity_warning: Any
severity_error: Any
number_of_entity_kinds: Any
all_entity_kinds: Any
all_definition_kinds: Any
all_declaration_kinds: Any
all_use_kinds: Any
all_occurrence_kinds: Any
number_of_occurrence_kinds: Any
