# GLOBAL SETTINGS
# ===============
# Configuration for mypy type checking
[mypy]
python_version = 3.13
warn_unused_configs = True
ignore_missing_imports = True
show_error_codes = True
follow_imports = skip
allow_untyped_globals = True

# Stricter checks for bpathlib module
[mypy-bpathlib.*]
disallow_untyped_defs = True
disallow_incomplete_defs = True
check_untyped_defs = True
warn_return_any = True
warn_redundant_casts = True
warn_unused_ignores = True
no_implicit_optional = True
strict_optional = True

# Ignore all other modules for now
[mypy-*]
ignore_errors = True

[mypy-components.*]
ignore_errors = True

[mypy-gui.*]
ignore_errors = True

[mypy-lexers.*]
ignore_errors = True


# KRISTOF MODULES
[mypy-dashboard.*]
ignore_errors = True

# [mypy-hardware_api.*]
# ignore_errors = True

[mypy-helpdocs.*]
ignore_errors = True

[mypy-home_libraries.*]
ignore_errors = True

[mypy-home_toolbox.*]
ignore_errors = True

[mypy-libmanager.*]
ignore_errors = True

# [mypy-toolmanager.*]
# ignore_errors = True

# [mypy-project.*]
# ignore_errors = True

[mypy-project_generator.*]
ignore_errors = True

[mypy-tree_widget.*]
ignore_errors = True

[mypy-sa_tab.*]
ignore_errors = True

# [mypy-wizards.*]
# ignore_errors = True

